name: grinch_data
description: A Data of abstrac Grinch

publish_to: none

version: 0.0.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  grinch_data_platform_interface:
    path: ../grinch_data_platform_interface

  grinch_data_web:
    path: ../grinch_data_web

  firebase_core: 0.5.3
  firebase_database: 4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: 1.10.0-nullsafety.3

flutter:
  plugin:
    platforms:
      web:
        default_package: grinch_data_web